### ISSUE TITLE
Which dataset is being refered to in the notebook?

### ISSUE THREAD

**Issue by NasonZ** [aulukelvin/LoRA_E5#2]
1st cell in the notebook:

```
import pandas as pd

random_state = 42
df = pd.read_csv('../data/quora_duplicate_questions.tsv', sep='\t')
df.sample(5)
```

Looking in the data folder, there is no such file.

Could you please clarify which dataset I should point to?

**Comment by aulukelvin** [comment]
Hi Nason,
The file failed to upload because it was too big (58MB). Please download the file with the link:
http://qim.fs.quoracdn.net/quora_duplicate_questions.tsv
